name: bridge
description: A new Flutter project.

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.0
  flame_input: ^1.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # Latest lint version for Dart 3.7

flutter:
  uses-material-design: true

  assets:
    - assets/
